### ISSUE TITLE
TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('<U32') dtype('<U32') dtype('<U32')

### ISSUE THREAD

**Issue by partha434** [YeoLab/MINES#18]
Hi
 While running the following code I got an error. Please help.

python genomic_MINES.py --ref reference.fasta --coverage_plus sm1.coverage.plus.bedgraph --fraction_modified_plus sm1.fraction_modified_reads.plus.wig.bed --coverage_minus sm1.coverage.minus.bedgraph --fraction_modified_minus sm1.fraction_modified_reads.minus.wig.bed --output sm1_m6A_mines.bed

Traceback (most recent call last):
  File "/home/partha/anaconda3/envs/mines/lib/python3.7/site-packages/pandas/core/ops.py", line 1012, in na_op
    result = expressions.evaluate(op, str_rep, x, y, **eval_kwargs)
  File "/home/partha/anaconda3/envs/mines/lib/python3.7/site-packages/pandas/core/computation/expressions.py", line 205, in evaluate
    return _evaluate(op, op_str, a, b, **eval_kwargs)
  File "/home/partha/anaconda3/envs/mines/lib/python3.7/site-packages/pandas/core/computation/expressions.py", line 65, in _evaluate_standard
    return op(a, b)
TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('<U32') dtype('<U32') dtype('<U32')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "genomic_MINES.py", line 110, in <module>
    df['key2'] = df['chr'] + ':' + df['start'].astype(str)
  File "/home/partha/anaconda3/envs/mines/lib/python3.7/site-packages/pandas/core/ops.py", line 1069, in wrapper
    result = safe_na_op(lvalues, rvalues)
  File "/home/partha/anaconda3/envs/mines/lib/python3.7/site-packages/pandas/core/ops.py", line 1033, in safe_na_op
    return na_op(lvalues, rvalues)
  File "/home/partha/anaconda3/envs/mines/lib/python3.7/site-packages/pandas/core/ops.py", line 1023, in na_op
    result[mask] = op(x[mask], y)
TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('<U32') dtype('<U32') dtype('<U32')

**Comment by dietvin** [comment]
Hi! 

I have the same problem running cDNA_MINES.py. My command:
```
python $MINESDIR/cDNA_MINES.py \
                --fraction_modified $OUTDIR/tombo_out.fraction_modified_reads.plus.wig.bed \
                --coverage $OUTDIR/tombo_out.coverage.plus.bedgraph \
                --output $OUTDIR/$name.out.bed \
                --ref $ref_fasta \
                --kmer_models $MINESDIR/Final_Models/GGACT_9_random_forest_model.pickle
```

Did you find a solution to the problem?
