### ISSUE TITLE
cDNA_MINES.py command error

### ISSUE THREAD

**Issue by aman21392** [YeoLab/MINES#5]
I used cDNA_MINES.py command and it gives me following error with command-
 python /home/aclab/apps/MINES/cDNA_MINES.py --fraction_modified control.fraction_modified_reads.plus.wig.bed --coverage control.coverage.plus.bedgraph --output m6A_control.bed --ref /home/aclab/nanopore_2nd_experiment/epinano/homotranscript.fa --kmer_models /home/aclab/apps/MINES/Final_Models/GGACT_9_random_forest_model.pickle
Traceback (most recent call last):
  File "/home/aclab/apps/MINES/cDNA_MINES.py", line 126, in <module>
    df=df.intersect(tmp, wb=True, wa=True)
  File "/home/aclab/.local/lib/python2.7/site-packages/pybedtools/bedtool.py", line 917, in decorated
    result = method(self, *args, **kwargs)
  File "/home/aclab/.local/lib/python2.7/site-packages/pybedtools/bedtool.py", line 401, in wrapped
    decode_output=decode_output,
  File "/home/aclab/.local/lib/python2.7/site-packages/pybedtools/helpers.py", line 455, in call_bedtools
    raise BEDToolsError(subprocess.list2cmdline(cmds), stderr)
pybedtools.helpers.BEDToolsError:
Command was:

        bedtools intersect -wb -wa -b control.coverage.plus.bedgraph -a /tmp/pybedtools.7RRdzW.tmp

Error message was:
Error: Invalid record in file /tmp/pybedtools.7RRdzW.tmp. Record is
ENST00000470729 109     GGACT   -15     94      95      +       0.2

I used your model which you provided in the MINEs program. I used transcript file for cDNA.py script run.

**I also doing this  by your providing example -**
python genomic_MINES.py --fraction_modified_plus HEK293_control_chrX.fraction_modified_reads.plus.wig.bed --coverage_plus HEK293_control_chrX.coverage.plus.bedgraph --output m6A.bed --ref hg19.fa  --coverage_minus HEK293_control_chrX.coverage.minus.bedgraph --fraction_modified_minus HEK293_control_chrX.fraction_modified_reads.minus.wig.bed
index file hg19.fa.fai not found, generating...
Traceback (most recent call last):
  File "genomic_MINES.py", line 232, in <module>
    df=df.intersect(tmp, wb=True, wa=True)
  File "/home/aclab/.local/lib/python2.7/site-packages/pybedtools/bedtool.py", line 917, in decorated
    result = method(self, *args, **kwargs)
  File "/home/aclab/.local/lib/python2.7/site-packages/pybedtools/bedtool.py", line 401, in wrapped
    decode_output=decode_output,
  File "/home/aclab/.local/lib/python2.7/site-packages/pybedtools/helpers.py", line 455, in call_bedtools
    raise BEDToolsError(subprocess.list2cmdline(cmds), stderr)
pybedtools.helpers.BEDToolsError:
Command was:

        bedtools intersect -wb -wa -b HEK293_control_chrX.coverage.plus.bedgraph -a /tmp/pybedtools.DVCoeb.tmp

Error message was:
Error: Invalid record in file /tmp/pybedtools.DVCoeb.tmp. Record is
chrX    100056326       GGACA   -15     100056311       100056312       +       1.0

 So please give suggestion, then i complete this pipeline. 
Thank you in advance

**Comment by PengNi** [comment]
I also met the same problem. Can anyone solve this?

Best, 
Peng

**Comment by PengNi** [comment]
It seems pandas orders columns as lexical order by default. 

Add `df = df[["chr", "start", "stop", "drach_coordinate", "drach_kmer", "pos", "strand", 4]]` under [line 119](https://github.com/YeoLab/MINES/blob/master/cDNA_MINES.py#L119) `df=df[df['start']>0]` will fix this.
